[pytest]
addopts = -v --html=e2e-report.html --self-contained-html --tracing=retain-on-failure --video=retain-on-failure --screenshot=only-on-failure
testpaths = tests
; base_url = https://hrms.syncrra.ai/dashboard
base_url = http://localhost:3000
pythonpath = .
